### ISSUE TITLE
Issue with cached language

### ISSUE THREAD

**Issue by keybeth** [jgpacheco/ngx-translate-cache#1]
I have an issue when I set a default language. I don't know why but the first `translateService.use(lang)` with the `browserLanguage` is setted after the `cachedLanguage` is setted too. My browser language is **es** and my cached language is **en**.

I call this function in my `AppComponent` constructor:
```typescript
    private initTranslations(): void {
      this.translate.onLangChange
        .map(event => event.lang)
        .subscribe(lang => this.langService.setLangAttribute(lang));
      this.translate.setDefaultLang('en');
      this.translateCacheService.init();
     }
```
I rewrite the `TranslateCacheService` modifying the `init` function to call `translateService.use(lang)` once. Now, that works for me!

```typescript
    public init(): void {
      ...
      const language = this.getCachedLanguage() || this.translateService.getBrowserLang();
      this.translateService.use(language);
    }
```

**Comment by jgpacheco** [comment]
@keybeth Could you open a PR?

I would recommend something like this:

```
    public init(): void {
      ...
      const language = this.getCachedLanguage() || this.translateService.getBrowserLang();
      if (language ) { this.translateService.use(language ); } // language could be 'undefined' at this point
    }
```

**Comment by zhukov-vlad** [comment]
@jgpacheco created a [PR ](https://github.com/jgpacheco/ngx-translate-cache/pull/4) for you. Also there is another PR to check if browser language is available in translate service before using it
