### ISSUE TITLE
Migrating to Angular with Ivy issue

### ISSUE THREAD

**Issue by Silvac34** [jgpacheco/ngx-translate-cache#21]
Hey, I got this issue when migrating to angular 9 with issue : 

   ERROR in node_modules/ngx-translate-cache/index.d.ts:5:51 - error NG6005: TranslateCacheModule.forRoot returns a ModuleWithProviders type without a generic type argument. Please add a generic type argument to the ModuleWithProviders type. If this occurrence is in library code you don't control, please contact the library authors.

    5     static forRoot(config: TranslateCacheConfig): ModuleWithProviders;
                                                        ~~~~~~~~~~~~~~~~~~~
    src/app/i18n/i18n.module.ts:42:14 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    Is it missing an @NgModule annotation?

    42 export class I18nModule {
                    ~~~~~~~~~~

Any fix ?

**Comment by AyazBelim** [comment]
I am facing the same issue for angular version 9. 
Hey @jgpacheco can you fix this ?

**Comment by dwikidw** [comment]
same issue here , any updates ?

**Comment by Silvac34** [comment]
I had to stop using this library ...
I implemented ngx-translate with angular universal modifying my code using [this tuto](https://itnext.io/how-to-create-search-engine-friendly-internationalized-web-apps-with-angular-universal-and-510c658f2e41)

**Comment by AndreyChayko** [comment]
Hey guys, will be great to have an update/fix for this ASAP
