### ISSUE TITLE
Support for Angular 13

### ISSUE THREAD

**Issue by anwarulislam** [jgpacheco/ngx-translate-cache#41]
Could you please upgrade library to support Angular 13?

**Comment by newshahn** [comment]
Any updates on this?

**Comment by duxor** [comment]
@jgpacheco I can update it to the latest version (angular 14) and make a PR if the project is still active?

**Comment by haidar-h** [comment]
@duxor We would appreciate it.  
```Processing legacy "View Engine" libraries:
- ngx-translate-cache [es2015/esm2015] (https://github.com/jgpacheco/ngx-translate-cache)
Encourage the library authors to publish an Ivy distribution.
```

**Comment by omikolaj** [comment]
part of the reason why I dislike to import packages from individuals. They go out of date after several releases. It adds tech debt for the future.

**Comment by duxor** [comment]
> @duxor We would appreciate it.
> 
> ```processing
> - ngx-translate-cache [es2015/esm2015] (https://github.com/jgpacheco/ngx-translate-cache)
> Encourage the library authors to publish an Ivy distribution.
> ```

PR is added, please check it: https://github.com/jgpacheco/ngx-translate-cache/pull/53

**Comment by dmihaita** [comment]
@duxor : Any chance to publish this package along with the pull request as a new package in npm registry? It seems that the original package is stalled.

**Comment by paulodrade** [comment]
Any update on this? Will the #53 PR be aprove?

**Comment by MasterJOI** [comment]
Wow, it's happening, I'm just using it with angular  v14, hope you add it soon too, thanks!

**Comment by haidar-h** [comment]
The following supports v16 https://www.npmjs.com/package/@haidar-h/ngx-translate-cache
