### ISSUE TITLE
checksum? 

### ISSUE THREAD

**Issue by mateBe95** [jgpacheco/ngx-translate-cache#8]
Hey folks, is it possible to verify when json files get changes? 
for example: 
1) change language to French (next time we get data from cache)
1) Add new translate when im on the website,
2) change language again to french detect (changes in file json) and make request (not from cache)

**Comment by jgpacheco** [comment]
Check out the documentation [ngx-translate](https://github.com/ngx-translate/core#properties). I think `onTranslationChange` event and `setTranslation` method could do the trick.
